# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-22 11:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='电影名')),
                ('url', models.CharField(max_length=300, verbose_name='电影链接')),
                ('score', models.CharField(max_length=10, verbose_name='评分')),
                ('actors', models.CharField(blank=True, max_length=300, null=True, verbose_name='演员')),
                ('decs', models.CharField(max_length=200, verbose_name='电影描述')),
                ('bofang_nums', models.CharField(max_length=20, verbose_name='播放量')),
                ('movie_img_url', models.CharField(max_length=300, verbose_name='图片链接')),
                ('create_time', models.DateTimeField(default=datetime.datetime(2018, 10, 22, 11, 19, 26, 487627), verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '电影',
                'verbose_name_plural': '电影',
            },
        ),
    ]
