# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-23 10:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_detail',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 23, 10, 7, 48, 620556), verbose_name='创建时间'),
        ),
    ]
